# Generated by Django 3.1.5 on 2021-02-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurestoran',
            name='category_menu',
            field=models.CharField(max_length=200),
        ),
    ]
